trigger:
  branches:
    include:
    - '*'  # Need to explicitly set this as we have path exclusions
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

stages:
- stage: Test
  jobs:
  - job: TestLinuxPSCore
    displayName: Linux PowerShell Core
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: pwsh -File ./build.ps1

  - job: TestWindowsPSDesktop
    displayName: Windows PowerShell Desktop
    pool:
      vmImage: windows-2019
    steps:
    - script: powershell.exe -File .\build.ps1

  - job: TestWindowsPSCore
    displayName: Windows PowerShell Core
    pool:
      vmImage: windows-2019
    steps:
    - script: pwsh.exe -File .\build.ps1

- stage: Publish
  jobs:
  - job: Publish
    displayName: PowerShell Module
    steps:
    - script: echo Publishing code
