trigger:
  branches:
    include:
    - '*'  # Need to explicitly set this as we have path exclusions
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

stages:
- stage: Test
  jobs:
  - job: TestLinuxPSCore
    displayName: Linux PowerShell Core
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: pwsh -File ./build.ps1
      env:
        CODECOV_TOKEN: $(codecov_token)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: Build/TestResults_PS*.xml
    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: jaCoCo
        summaryFileLocation: Build/Coverage_PS*.xml

  - job: TestWindowsPSDesktop
    displayName: Windows PowerShell Desktop
    pool:
      vmImage: windows-2019
    steps:
    - script: choco.exe install codecov --yes --no-progress
    - script: powershell.exe -File .\build.ps1
      env:
        CODECOV_TOKEN: $(codecov_token)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: Build/TestResults_PS*.xml
    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: jaCoCo
        summaryFileLocation: Build/Coverage_PS*.xml


  - job: TestWindowsPSCore
    displayName: Windows PowerShell Core
    pool:
      vmImage: windows-2019
    steps:
    - script: choco.exe install codecov --yes --no-progress
    - script: pwsh.exe -File .\build.ps1
      env:
        CODECOV_TOKEN: $(codecov_token)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: Build/TestResults_PS*.xml
    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: jaCoCo
        summaryFileLocation: Build/Coverage_PS*.xml

- stage: Publish
  jobs:
  - job: Publish
    displayName: PowerShell Module
    steps:
    - script: echo Publishing code
