jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
- job: Windows PS Desktop
  pool:
    vmImage: windows-2019
- job: Windows PS Core
  pool:
    vmImage: windows-2019

steps:
- script: echo Hello, World!
