# Template for the module build process. The job has the following steps;
#
#     1. Run the ./build.ps1 script to test the module with the psake build
#     2. Publish the Pester test results to Azure Pipelines
#     3. Publish the Build folder for that node which contains the processed module ready for publishing.
# The following parameters must be defined for the job to run
# parameters:
#   jobName: The name of the job, A-Z, a-z, 0-0, and underscore
#   displayName: The friendly name of the job that is displayed in the UI and used for the artifact name
#   vmImage: The name of the VM Image to use
#   executable: The path to the PowerShell binary to run the build again


jobs:
- job: Build_${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: ${{ parameters.executable }} -File ./build.ps1
    displayName: Run tests
    env:
      CODECOVE_TOKEN: $(codecov_token)

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: Build/TestResults_PS*.xml

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: ${{ parameters.displayName }}
      targetPath: Build
