jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: pwsh -File ./build.ps1

- job: Windows_PS_Desktop
  pool:
    vmImage: windows-2019
  steps:
  - script: powershell.exe -File .\build.ps1

- job: Windows_PS_Core
  pool:
    vmImage: windows-2019
  steps:
  - script: pwsh.exe -File .\build.ps1
