jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: echo Hello from Ubuntu

- job: Windows_PS_Desktop
  pool:
    vmImage: windows-2019
  steps:
  - script: echo Hello from Windows Desktop

- job: Windows_PS_Core
  pool:
    vmImage: windows-2019
  steps:
  - script: echo Hello from Windows Core
